### PR TITLE
Fix(token-update): check if token has been deleted

### LINKED ISSUE #45: Ensure token delete checks on deleted Token
Once deleted update, mint, burn, wipe, freeze, unfreeze, grant kyc, revoke kyc and token transfer transactions must resolve to TOKEN_WAS_DELETED

### LINKED ISSUE #47: Research - Performing Wipe/Freeze/Unfreeze/KYC/UnKYC on token, creation of token <> account references
- What happens if the account does not have reference to the token and freeze/unfreeze/wipe etc operations are performed. Will there be relationship created? - almost certainly, BUT is there an attack vector such as:

User A creates 1000 tokens, spams an address with frozen/unfrozen/kyc or any kind of tx that will create a relationship between the acc and the token. Max relations will be created, thus the account won't be able to acquire tokens

### PR DESCRIPTION
**Pull request by failfmi**
**Related issue(s)**:
Closes #45 

**Summary of the change**:
- Add check if token has been deleted
- Add tests

**Applicable documentation**
- [ ] Javadoc
- [ ] HAPI protobuf comments
- [ ] README

### CODE REVIEW

File: test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java [hunk 1]
```diff
@@ -64,10 +65,28 @@ public static void main(String... args) {
...
 				}
 		);
 	}
 
+	private HapiApiSpec validatesAlreadyDeletedToken() {
+		return defaultHapiSpec("ValidatesAlreadyDeletedToken")
+				.given(
+						newKeyNamed("adminKey"),
+						cryptoCreate(TOKEN_TREASURY),
+						cryptoCreate("payer")
```
Comment (Daniel-K-Ivanov) [inline test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java:78]: I think that you do not need the "payer" created

**Review by Daniel-K-Ivanov — CHANGES_REQUESTED** [review]

**Review by Daniel-K-Ivanov — APPROVED** [review]
